version: "3.8"

services:
  db:
    image: postgres:17.6-alpine3.22
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-master-golang}
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-root}"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pgdata:
    driver: local
